In [2]:
print("Helloworld")

Helloworld


In [1]:
print("Line1")
print("Line2")

Line1
Line2


In [3]:
%history

print("Line1")
print("Line2")
print("Helloworld")
%history


In [4]:
# %load xyz.py
print("Line1")
print("Line2")
print("Line3")
print("From other file")


Line1
Line2
Line3
From other file


In [5]:
%run xyz.py

Line1
Line2
Line3
From other file


In [6]:
%time print("ada")

ada
Wall time: 0 ns


# Python

In [7]:
%time l1 = list(range(1,3000000))
print(l1[:10])

Wall time: 67.8 ms
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [8]:
%time [x+5 for x in l1][:10]

Wall time: 303 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [9]:
for i, e in list(enumerate(l1)):
    l1[i] = l1[i] + 5
l1[:10]    

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [10]:
for i, e in list(enumerate(l1)):
    l1[i] += 5
l1[:10]  

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
l1 = [[1,2,3],
     [4,5,6],
     [7,8,9]]

print("Before Adding 5")
print(l1)
print()
for ri, rd in list(enumerate(l1)):
    for ci, cd in list(enumerate(rd)):
        l1[ri][ci] += 5
print("After Adding 5")
print(l1)

In [ ]:
l1 = [1,2,4]
l1 + 5

# Numpy 

In [11]:
def abc():print("pakistan") #python
def abc():print("Hello World") #Numpy
    
abc()

Hello World


In [2]:
# import numpy as *
import numpy as np

In [13]:
l = [1,3,2]
print(sum(l)) # python function
print(np.sum(l)) # Numpy function

6
6


In [14]:
l1 = np.arange(1,3000000)
%time l1 + 5

Wall time: 8 ms


array([      6,       7,       8, ..., 3000002, 3000003, 3000004])

In [15]:
l1 = np.arange(1,13)


print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)
l1

Diminsion: 1
Type: int32
Size: 12
Itemsize: 4
Shape: (12,)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
l1 = np.array(1)


print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)
l1

Diminsion: 0
Type: int32
Size: 1
Itemsize: 4
Shape: ()


array(1)

In [18]:
# 1D array
l1 = np.array([1,5])


print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)
l1

Diminsion: 1
Type: int32
Size: 2
Itemsize: 4
Shape: (2,)


array([1, 5])

In [19]:
# 2D array
l1 = np.array([[1,5],
               [8,9]])


print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)
l1

Diminsion: 2
Type: int32
Size: 4
Itemsize: 4
Shape: (2, 2)


array([[1, 5],
       [8, 9]])

In [16]:
np.array??

# A Multidimensional Array Object

In [3]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
# -1 represent remaining data
# 6 is row
np.arange(1,13).reshape((6,-1))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [5]:
np.arange(1,13).reshape((4,-1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
 #l1 = np.arange(1,13).reshape((4,3))
# l1 = np.arange(1,13).reshape((3,4))
# l1 = np.arange(1,13).reshape((2,6))
# l1 = np.arange(1,13).reshape((6,2))
# l1 = np.arange(1,13).reshape((12,1))

l1 = np.arange(1,13).reshape((6,-1))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Diminsion: 2
Type: int32
Size: 12
Itemsize: 4
Shape: (6, 2)


In [8]:
l1 = np.arange(1,13).reshape((6,-1))
l1.shape = (2,6)
l1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

<img src="https://www.pythoninformer.com/img/numpy/3d-array-stack.png">
<img src="https://www.pythoninformer.com/img/numpy/3d-array.png">

In [9]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Diminsion: 3
Type: int32
Size: 27
Itemsize: 4
Shape: (3, 3, 3)


In [10]:
np.arange(4*3*2*2).reshape((4,3,2,2))

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35]]],


       [[[36, 37],
         [38, 39]],

        [[40, 41],
         [42, 43]],

        [[44, 45],
         [46, 47]]]])

In [12]:
np.arange(3*2*3*2*2).reshape((3,2,3,2,2))

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]]],


        [[[12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]]],



       [[[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]],

         [[32, 33],
          [34, 35]]],


        [[[36, 37],
          [38, 39]],

         [[40, 41],
          [42, 43]],

         [[44, 45],
          [46, 47]]]],



       [[[[48, 49],
          [50, 51]],

         [[52, 53],
          [54, 55]],

         [[56, 57],
          [58, 59]]],


        [[[60, 61],
          [62, 63]],

         [[64, 65],
          [66, 67]],

         [[68, 69],
          [70, 71]]]]])

In [13]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
# l1[i,j,k]
# l1[slide, row, column]
# l1[2]
# l1[1,2]
l1[1,2,1]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


17

In [14]:
l1[1][2][0]

16

In [15]:
l1 = np.array(['a','b','c'])
print(l1)
#   0      1      2
l1[[True, False, True]]

['a' 'b' 'c']


array(['a', 'c'], dtype='<U1')

In [18]:
ages = np.arange(1,80)
jawan = []
for age in ages:
    if age > 25:
        jawan.append(True)
    else:
        jawan.append(False)
    
jawan

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [19]:
ages[jawan]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79])

In [21]:
ages[ages > 25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79])

In [23]:
ages= list(range(1,100))
print(type(ages))
ages

<class 'list'>


[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [24]:
# This opreation is not supported in list
ages[ages > 25]

TypeError: '>' not supported between instances of 'list' and 'int'

In [25]:
l1 = np.arange(1,28).reshape((3,3,3))
print(l1)
l1[l1 % 6 == 0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 6, 12, 18, 24])

In [26]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print(l1[l1 % 3 == 0])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[ 3  6  9 12 15 18 21 24 27]


In [27]:
l1 % 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [30]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
l1[(l1 % 3 == 0)  & (l1 % 9 == 0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 9, 18, 27])

In [31]:
l1 = np.random.randn(3,3,3,3)

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[[ 1.04725748  0.65399846 -0.44736759]
   [-1.59796347 -0.17352479 -0.20983283]
   [-3.04050852 -0.96527261 -0.65316936]]

  [[-0.43480611 -0.0965851  -0.54658819]
   [-0.5553209  -2.01671929 -1.53758011]
   [ 0.267692    1.38370185  0.08954641]]

  [[ 0.21640243 -0.94441645  0.8982768 ]
   [-1.36985426  1.63322461  0.05067112]
   [-0.95588714  0.63802627 -0.50104964]]]


 [[[ 1.70122731 -0.15127754 -0.85044111]
   [-0.09648863 -0.04384449 -0.43933995]
   [-0.13812089  0.43831461 -0.79992703]]

  [[-0.34859829  0.22798332  0.61552581]
   [ 0.13818522  1.0451642   0.91255951]
   [-0.06877916 -0.54194454  1.63839795]]

  [[ 0.7624983   0.09446874 -0.60629275]
   [ 0.10350566 -0.58266009 -0.28053853]
   [ 0.47625899  0.46286298 -0.10043574]]]


 [[[-1.73760785  0.06080503  1.73190416]
   [ 1.50615335  1.18080662 -0.33561917]
   [-0.63822067  0.26270706  0.09860268]]

  [[-0.17528278  0.91001984 -0.18157026]
   [ 1.37169878 -0.37181072 -1.03546417]
   [ 1.97830263 -1.65160884 -1.96190713

In [ ]:
# l1 + 2
# l1 * 2
#l1 / 2
#l1 ** 2
#l1 ** 0.5
#l1 % 2

# Creating ndarrays

##### np.array()

In [33]:
# Deep Copy(Always copy)
l = [1,2,3]

a = np.array(l)
b = np.array(a)

print(a is l) #False
print(b is a) #False
print(a is a)
print(id(a) == id(a))
print(id(a) == id(b))

False
False
True
True
False


In [34]:
# 1 array->Same Datatype->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy
l = [1,2,3]
print(type(l))

a = np.asarray(l) #3
b = np.asarray(a) #1 
c = np.asarray(a, dtype=np.float64)#2

print(a is b) # 2
print(l is a) # 1
print(c is a) # 3
type(a)

<class 'list'>
True
False
False


numpy.ndarray

In [35]:
import numpy as np
a = np.array([1,2])
a.itemsize

4

In [ ]:
import numpy as np

## Creating ndarrays

In [38]:
a = np.array([1,3,4])
b = np.asarray([1,3,5])
print(a)
print(b)

[1 3 4]
[1 3 5]


In [39]:
a = np.arange(1,14)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

# Chaining

In [41]:
range??

In [43]:
def A(x):return x+5
def B(x):return x+6    
def C(x):return x+7    

In [44]:
C(B(A(1))) #1+5=6  6+6=12 12+7=19

19

In [45]:
A(B(C(1)))

19

np.A().B().C()

In [ ]:
#arange().reshape()
#np.ones
#np.ones_like
#np.zeros
#np.zeros_like
#np.full
#np.full_like
#np.empty
#np.empty_like

In [46]:
a = np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [47]:
b = np.reshape(a, (27,1))
b

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27]])

In [52]:
a = np.arange(1,28)
a.reshape(3,3,3)
print(a)
print(a.ndim)
a.shape = (3,9)
#a = a.reshape(3,3,3)
print(a.ndim)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
1
2


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [53]:
a.shape = (3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [60]:
a.shape = (3,9)

In [61]:
a.shape

(3, 9)

In [58]:
np.zeros((3,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [66]:
a.shape[0]

3

In [62]:
np.zeros((a.shape[0], a.shape[1]))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
np.zeros((a.shape))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
np.zeros(a.shape)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [73]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [71]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [76]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
b = np.ones_like(a)
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [78]:
b = np.ones_like(a) * 5 # + 5
b

array([[5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [79]:
b = np.full((3,3), 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# checkpoint 3-5-2021

In [ ]:
b = np.full_like(a, 5)
b

In [ ]:
a

In [ ]:
np.full_like(a, dtype=a.dtype, fill_value=2.5)

In [ ]:
np.full_like(a, dtype=np.float64, fill_value=2.5)

In [ ]:
np.empty((3,9))

In [ ]:
np.empty_like(a)

In [ ]:
np.full_like(a, 1) * np.nan


In [ ]:
np.full(a.shape, np.nan)

In [ ]:
np.eye(6)

In [ ]:
np.identity(3)

# Data Types for ndarrays

In [ ]:
a = np.array([1,3,4], dtype='int')
a.dtype

In [ ]:
a = np.array([1,3,4], dtype=int)
a.dtype

In [ ]:
a = np.array([1,3,4], dtype=np.int64)
a.dtype

In [ ]:
a = np.array([1,3,4], dtype='i1')
a.dtype

In [ ]:
b = np.array([3,8,9], dtype=a.dtype)
b.dtype

In [ ]:
c = a.astype(np.int64)
c.dtype

# Boolen Operation

In [ ]:
a = np.arange(1,28).reshape((3,3,3))
a

In [ ]:
a % 3 == 0

In [ ]:
print(a)
a[a%3==0]

In [ ]:
print(a)
a[(a%3==0) & (a%5==0)]

In [ ]:
print(a)
a[~a%3==0]

In [ ]:
print(a)
a[~(a%3==0)]

In [ ]:
print(a)
a[a%3!=0]

In [ ]:
a = np.arange(1,7).reshape((2,3,1))
a

# Fancy Slicing

In [ ]:
import numpy as np

In [ ]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)
a[[2,0,1]]


In [ ]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)

print("=====")
# print(a[[1,2,0]])
# print(a[[1,2,0]])
# a[[0,1,2],[0,1,2]]
# a[[1,2,0]][:,[2,1,0]]
# a[[1,2,0]][:,[-1,0]]
# a[[1,2,0],:,::-1]
a[::-1]
#a[:,::-1,:]

In [ ]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")

In [ ]:
names == "Qasim"

In [ ]:
data[[ True, False, False, False,  True, False]]

In [ ]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")

print()
data[names=="Qasim"]

In [ ]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names=="Qasim") |  (names=="Ali")]

In [ ]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names!="Qasim") |  (names!="Ali")]

In [ ]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names=="Qasim") |  (names=="Ali")][:,[0,-1]]

In [ ]:
l = [1,3,5,3,5]
l[:3]
l[:3] = 5

In [ ]:
l = [1,3,5,3,5]
l[:3]
l[0] = 5
l

In [ ]:
l = np.array([1,3,5,3,5])
l[:3]
l[:3] = 5
l

In [ ]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(8):
    a[i] = i
print(a)    

In [ ]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(len(a)):
    a[i] = i
print(a) 

In [ ]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(a.shape[0]):
    a[i] = i
print(a)

In [ ]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i, _ in enumerate(a):
    a[i] = i
print(a)

# Transposing Arrays and Swapping Axes

In [ ]:
a = np.arange(4*3).reshape(4,3)
print(a)

In [ ]:
a.T

In [ ]:
a.T.T.T.T

In [ ]:
a

In [ ]:
a.transpose()

In [ ]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a * b

In [ ]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a @ b

In [ ]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a.dot(b)

In [ ]:
a.dot(np.ones_like(a).T)

In [ ]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.T

In [ ]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.transpose(2,1,0)

In [ ]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
#a.reshape(a.shape[2], a.shape[1])
a.swapaxes(2,1)

# Table 4-3. Unary ufuncs

In [ ]:
a = np.array([7,8,-20,2,-3,20])
np.abs(a)

In [ ]:
a = np.array([7,8,-20,2,-3,20])
np.fabs(a)

In [ ]:
a = np.array([36,25,16])
np.fabs(a)

In [ ]:
a = np.array([7,8,-20,2,-3,20])
np.square(a)

In [ ]:
np.exp(a)

In [ ]:
a = np.array([2.3, 2.1,2.9, 2.8])
np.ceil(a)

In [ ]:
a = np.array([2.3, 2.1,2.9, 2.8])
np.floor(a)

In [ ]:
a = np.array([2.8, 9.7, 5.9])
for i in a:
    i = str(i).split(".")
    print(i[0], i[1])

In [ ]:
a = np.array([2.8, 9.7, 5.9])
f, w = np.modf(a)
print(w,f, sep="\n")

In [ ]:
np.isnan(np.nan)

In [ ]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])
c = np.array([4,0,2,1])

np.maximum(a,b,c)

In [ ]:
np.fmax(a,b,c)

In [ ]:
np.fmax??

# 4.3 Array-Oriented Programming with Arrays

In [ ]:
a = np.arange(4*3)
print(a)

In [ ]:
np.meshgrid(a,a)

# Expressing Conditional Logic as Array Operations

#### np.where(condition, value_true, value_false)

In [ ]:
a = np.arange(8*4).reshape((8,4))
a

In [ ]:
np.where(a%3 == 0, "Yes","No")

In [ ]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])

np.where(a>b, a, b)

# Mathematical and Statistical Methods

In [ ]:
a = np.arange(3*4).reshape((3,4))
a

In [ ]:
np.sum(a)

In [ ]:
print(a)
np.sum(a, axis=0)

In [ ]:
print(a)
np.sum(a, axis=1)

##### Broad Casting

In [ ]:
a = np.arange(5*5).reshape((5,5))
print(a)
a + 5

In [ ]:
a = np.arange(5*5).reshape((5,5))
b = np.full_like(a, 5)
print(a,b,sep="\n\n")
a + b

## stacking

#### split

# > Stackig

In [ ]:
import numpy as np
a = np.random.randint(1,10, size=10)
b = a + 5
print(a, b, sep='\n')
print(len(a),len(b))

In [ ]:
print(a,b, sep='\n\n')

In [ ]:
print(a,b, sep='\n\n')
np.stack((a,b), axis=0)

In [ ]:
print(a,b, sep='\n\n')
np.stack((a,b), axis=1)

In [ ]:
# np.stack((a,b), axis=1)
np.column_stack((a,b))

In [ ]:
np.stack((a,b), axis=0)

In [ ]:
np.vstack((a,b))

In [ ]:
# 
# 
np.row_stack((a,b))

In [ ]:
np.hstack((a,b))

In [ ]:
np.vstack((a,b))

In [ ]:
b = np.arange(3*3).reshape((3,3)) 
a = a + 5
print(a, b, sep='\n\n')

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b))

In [ ]:
np.column_stack((a,b))

In [ ]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 7
print(a,b, sep='\n->SecondArray->\n')
np.dstack((a,b))

In [ ]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 7
print(a,b, sep='\n->SecondArray->\n')
np.stack((a,b), axis=2)

In [ ]:
np.stack??

In [ ]:
a.reshape((2,-1))

# Split

In [ ]:
a = np.arange(6*6).reshape((6,6))
print(a)
# np.split(a, 6, axis=0)
# np.split(a, 3, axis=0)
np.split(a, 2, axis=0)

In [ ]:
a = np.arange(6*6).reshape((6,6))
print(a)
np.split(a, 6, axis=1)
np.split(a, 3, axis=1)
np.split(a, 2, axis=1)[0]

In [ ]:
a = np.arange(2*2*2).reshape((2,2,2))
p=print(a)

np.dsplit(a, 2)

# Table 4-6. Array set operations

In [ ]:
a = np.random.randint(1,10, size=20)
print(a)
np.unique(a)

In [ ]:
piaic = np.random.randint(1,100, size=30)
cnic = np.random.randint(1,10, size=5)
print(piaic, cnic,sep='\n\n')

In [ ]:
[True if x in piaic else False for x in cnic]

In [ ]:
[x in piaic for x in cnic]

In [ ]:
["Yes" if x in piaic else "NO" for x in cnic]

In [ ]:
print(piaic, cnic,sep='\n\n')
np.in1d(cnic, piaic)


In [ ]:
print(piaic, cnic,sep='\n\n')
c = np.in1d(cnic, piaic)
np.where(c==True,"Yes","No")

In [ ]:
print(piaic, cnic,sep='\n\n')
np.intersect1d(cnic, piaic)

In [ ]:
print(piaic, cnic,sep='\n\n')
np.union1d(cnic, piaic)

In [ ]:
print(piaic, cnic,sep='\n\n')
np.setdiff1d(cnic, piaic)

In [ ]:
# XOR
# 0 0 -> 0
# 1 0 -> 1
# 0 1 -> 1
# 1 1 -> 0
print(piaic, cnic,sep='\n\n')
np.setxor1d(cnic, piaic)